export const DAILY_QUOTES = [
  "Protecting capital today gives you the opportunity to trade tomorrow.",
  "A good trader does not need to predict every move; they only need to execute their edge consistently.",
  "Patience is not waiting for a trade; it is waiting for the right trade.",
  "The market does not owe you a setup, and you do not owe the market a trade.",
  "Risk management comes before profit management.",
  "A small controlled loss is a business expense, not a personal failure.",
  "Trade the setup you planned, not the emotion you feel.",
  "Discipline means following your rules when breaking them looks tempting.",
  "Your job is not to control the market; your job is to control your decisions.",
  "One high-quality setup is worth more than ten forced trades.",
  "Consistency is built by repeating good decisions, not by repeating profitable outcomes.",
  "Never risk tomorrow’s opportunity trying to recover today’s loss.",
  "The best trade is sometimes the trade you choose not to take.",
  "A trader becomes dangerous when impatience becomes stronger than their plan.",
  "Capital preservation keeps you in the game long enough for your edge to work.",
  "Do not increase risk because you are angry; reduce exposure because you are emotional.",
  "A setup is not valid simply because you want it to work.",
  "Let price confirm your idea instead of forcing price to fit your idea.",
  "The market rewards preparation more consistently than prediction.",
  "Your stop-loss is not your enemy; uncontrolled risk is.",
  "A losing trade can still be a good trade when it follows the plan.",
  "A winning trade can still be a bad trade when it breaks the rules.",
  "Master your execution before trying to master the market.",
  "Overtrading usually begins when patience ends.",
  "Revenge trading turns one mistake into a sequence of mistakes.",
  "The goal is not to trade more; the goal is to trade better.",
  "High conviction should come from evidence, not excitement.",
  "Your risk should be decided before your entry, not after it.",
  "When the setup disappears, your trade should disappear with it.",
  "Do not chase price after missing an entry; another opportunity will exist.",
  "A trader who respects small losses avoids creating large problems.",
  "Probability matters more than certainty in trading.",
  "The market can remain irrational longer than your prediction can remain relevant.",
  "Your trading plan is valuable only when you follow it under pressure.",
  "The strongest traders are not those who avoid losses, but those who manage them.",
  "Liquidity creates opportunity, but discipline determines whether you can capture it.",
  "Do not enter because liquidity was taken; wait for your confirmation.",
  "A liquidity sweep is information, not an automatic entry signal.",
  "Market structure should guide your bias, not dictate your emotions.",
  "Wait for confirmation when the market has not yet shown its hand.",
  "Price action becomes clearer when emotion is removed from the chart.",
  "Do not confuse movement with opportunity.",
  "Every candle tells a story; your job is to read it without forcing a conclusion.",
  "A clean chart often reveals more than a crowded chart full of indicators.",
  "Structure first, entry second, risk always.",
  "The best entries are usually planned before price reaches them.",
  "If your setup requires hope, it is probably not a setup.",
  "Trade your rules, not the last trade.",
  "One loss does not change your edge; abandoning your process can.",
  "Do not let a losing streak convince you to abandon a proven process.",
  "When emotions rise, position size should never rise with them.",
  "Confidence comes from preparation, not from predicting the next candle.",
  "Trading psychology begins with accepting that you cannot control the outcome.",
  "Detach your self-worth from your trading results.",
  "A trader who accepts uncertainty makes better decisions under pressure.",
  "Fear often makes traders exit good trades; greed makes them hold bad ones.",
  "Your emotions are data about yourself, not signals from the market.",
  "If you cannot accept the loss before entering, you are risking too much.",
  "Calm execution is a competitive advantage.",
  "The market does not know your entry price, your target, or your expectations.",
  "Never move your stop-loss simply because you dislike the outcome.",
  "A wider stop does not make a trade safer; appropriate position sizing does.",
  "Risk less when uncertainty is high.",
  "Protecting a trading account is more important than proving a trading idea correct.",
  "Your account grows when your risk stays controlled while your edge plays out.",
  "Never let one trade become important enough to change your rules.",
  "The professional mindset measures success by process before profit.",
  "Good trading is often boring because discipline removes unnecessary decisions.",
  "The fewer forced decisions you make, the fewer unnecessary mistakes you create.",
  "Trading is a probability game; your responsibility is to manage the odds and the risk.",
  "You do not need to catch the entire move; you only need to capture your planned portion.",
  "Missing a trade costs nothing; forcing a trade can cost your account.",
  "If the market moves without you, let it go.",
  "A missed opportunity is better than a poorly managed position.",
  "The market will provide another setup; your capital must survive until then.",
  "Trade less when your mind is unclear.",
  "After consecutive losses, protecting your decision-making ability matters more than finding another trade.",
  "Know when to stop trading for the day.",
  "A daily loss limit protects you from emotional decisions disguised as recovery attempts.",
  "Do not turn trading into gambling by increasing size after a loss.",
  "Your strategy needs enough trades to be judged fairly.",
  "Judge your strategy over a meaningful sample size, not one trade.",
  "One trade is an event; a hundred trades reveal a process.",
  "A trading journal turns experiences into measurable information.",
  "Review your mistakes without judging yourself; improvement requires honest feedback.",
  "The purpose of a journal is not to remember trades, but to understand decisions.",
  "Track your behavior, not just your profit and loss.",
  "Your biggest trading improvement may come from eliminating one repeated mistake.",
  "A strategy becomes powerful when execution becomes consistent.",
  "Do not change your strategy every time the market produces an unexpected result.",
  "Adapt your process when evidence changes, not when emotions change.",
  "There is no perfect strategy; there is only a strategy you understand and execute well.",
  "Simplicity makes discipline easier to maintain.",
  "A trader who knows their edge also knows when their edge is absent.",
  "No setup is better than a setup that violates your rules.",
  "Money is a consequence of good decisions, not the reason to abandon them.",
  "The goal of trading is not excitement; the goal is controlled participation.",
  "Professional trading is the ability to remain disciplined when the market becomes emotional.",
  "Your greatest trading advantage may simply be the ability to wait.",
  "The goal of a successful trader is to make good trades. Money is secondary.",
];

export function getDailyQuoteIndex(): number {
  const today = new Date();
  const epoch = new Date(1970, 0, 1);
  const currentLocalMidnight = new Date(today.getFullYear(), today.getMonth(), today.getDate());
  const diffDays = Math.floor(
    (currentLocalMidnight.getTime() - epoch.getTime()) / (1000 * 60 * 60 * 24),
  );
  return diffDays % DAILY_QUOTES.length;
}
