export const goldenRules: string[] = [
  "Protect your capital first. Opportunities will always come back.",
  "The market rewards patience, not prediction.",
  "Your job is not to predict the market, your job is to execute your edge.",
  "Amateurs focus on how much they can make. Professionals focus on how much they can lose.",
  "If you cannot control your emotions, you cannot control your money.",
  "Do not trade what you think, trade what you see.",
  "A missed opportunity is better than a realized loss.",
  "The hardest thing in trading is doing nothing when there is nothing to do.",
  "Consistency is the byproduct of discipline, not intelligence.",
  "Don't marry a trade; divorce it the moment it violates your plan.",
  "Your edge is only as good as your ability to execute it without hesitation.",
  "Fear of missing out (FOMO) is the quickest way to blow an account.",
  "A winning trade does not mean you made a good decision. A losing trade does not mean you made a bad one.",
  "Trade the market in front of you, not the one you want to see.",
  "Accept the risk before you take the trade. If you can't accept it, don't take it.",
  "The goal is not to be right every time, but to make money when you are right and lose little when you are wrong.",
  "Revenge trading is a fight you will always lose.",
  "If you are feeling euphoric after a win, step away. Arrogance precedes the worst losses.",
  "Never average down a losing position. A loser is a loser.",
  "Trading is 10% strategy, 10% execution, and 80% psychology.",
  "A stop loss is not a suggestion, it is your business insurance.",
  "When in doubt, stay out.",
  "Good trading should be boring, not thrilling.",
  "Your strategy works. Your discipline is what’s broken.",
  "Do not force trades. Let the market come to your levels.",
  "Respect the trend. Trying to catch the bottom is like trying to catch a falling knife.",
  "Focus on the process, not the profit.",
  "A trade is not an investment. It is a high-probability bet with a defined exit.",
  "You are one bad habit away from losing everything you’ve built.",
  "Cut your losses fast. Let your winners run.",
  "Every trade you take should have a defined risk-to-reward ratio before entry.",
  "Stop trying to outsmart the market. The market is always right.",
  "Your account size does not determine your skill; your consistency does.",
  "Do not let a green day turn into a red day because of greed.",
  "The best traders are the best losers. They lose small and move on.",
  "Overtrading is a symptom of impatience.",
  "Always plan your trade and trade your plan.",
  "If the setup is not perfect, reduce your risk or don't take the trade.",
  "Drawdowns are part of the business. How you handle them defines your career.",
  "Don't check your PnL during a trade. Focus on the structure.",
  "A strategy is useless without the discipline to follow it.",
  "Hesitation will cost you as much as impulsiveness.",
  "The market does not owe you anything. You must extract your profits.",
  "If you don't know who you are, the market is an expensive place to find out.",
  "Trading is an exercise in probability, not certainty.",
  "Never turn a day trade into a swing trade just because it went into drawdown.",
  "The best defense against a volatile market is a tight stop loss.",
  "Every setup looks perfect in hindsight. Trade the live chart.",
  "Stop trying to make money every day. Focus on making good trades.",
  "If you break your rules and win, you are reinforcing a habit that will eventually destroy you.",
  "Capital preservation is more important than capital appreciation.",
  "Don't rush the process. A trading career is built over years, not days.",
  "The bigger the loss, the harder it is to recover mathematically.",
  "Your biggest enemy in the market is the person staring back at you in the mirror.",
  "Trade small until you prove to yourself you can be consistent.",
  "The less you trade, the better your results usually are.",
  "Don't trade to get rich quick. Trade to build sustainable wealth.",
  "A clear mind is your most valuable trading tool.",
  "If you are trading with money you can't afford to lose, you have already lost.",
  "The market is a mechanism for transferring wealth from the impatient to the patient.",
  "Stop loss orders remove emotion from the exit decision.",
  "The trend is your friend until it bends at the end.",
  "Don't let a winning streak make you feel invincible.",
  "Every loss is a lesson if you choose to learn from it.",
  "You cannot control the outcome, only your execution and risk.",
  "Do not trade when you are angry, tired, or distracted.",
  "A good trader manages risk. A bad trader focuses only on profits.",
  "Take profits when the market gives them to you, not when you think it should.",
  "If a trade goes against you immediately, trust your stop loss.",
  "Don't let yesterday's loss affect today's execution.",
  "The market moves in phases. Your strategy must align with the current phase.",
  "There is always another trade. Never risk it all on one setup.",
  "Keep your journal accurate. Your journal is your best mentor.",
  "You are paying for an education every time you take a loss.",
  "The easiest way to make money is to stop losing money on stupid trades.",
  "A setup is only a setup if it meets ALL your criteria.",
  "Don't anticipate the signal. Wait for the confirmation.",
  "If you are confused by price action, the best position is cash.",
  "Trading is a game of survival. Survive long enough, and the edge plays out.",
  "Your risk should be fixed, your reward should be open.",
  "Don't chase breakouts blindly. Look for the retest.",
  "A tight stop loss on a bad entry is still a bad trade.",
  "If you have to force a reason to take a trade, it's not a trade.",
  "Let the market prove you right. Don't try to prove the market wrong.",
  "The best setups are the ones that jump off the chart at you.",
  "If you feel anxiety while in a trade, your position size is too large.",
  "Trading smaller sizes allows your edge to play out without emotional interference.",
  "Never let a substantial profit turn into a loss. Move your stops.",
  "The market is designed to trigger your emotions. Design your plan to ignore them.",
  "Discipline is doing what you need to do, even when you don't want to do it.",
  "A professional trader is essentially a professional risk manager.",
  "Do not trade the news. Trade the market's reaction to the news.",
  "If your system gives a signal, take it without hesitation.",
  "The hardest part of trading is trusting your edge during a drawdown.",
  "A winning trade feels good, but a well-executed trade builds your career.",
  "Focus on the next 100 trades, not the next 1 trade.",
  "The only holy grail in trading is risk management.",
  "Do not compare your Chapter 1 to someone else's Chapter 20.",
  "You don't get paid for predicting. You get paid for executing.",
  "In trading, the most boring approach is usually the most profitable one.",
];
